### ISSUE TITLE
Allow `external` signatures

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#253]
Sooner rather than later we will want to allow "assuming" types for functions from other crates /stdlib that are _not_ part of `flux`. For example, we want to allow some refined signature for `arr.len()` that lets us check the code.

```rust
pub fn bar(arr: &[i32]) -> i32 {
    let n = arr.len();
    if 0 < n {
        arr[0]
    } else {
        0
    }
}
```

**Comment by ranjitjhala** [comment]
Or we can just let `copilot` generate that code for us :-) 

<img width="347" alt="otoh" src="https://user-images.githubusercontent.com/1650232/208262962-e83a9c96-c75f-4365-add3-5d5563887209.png">

**Comment by nilehmann** [comment]
For the most part, I think this is solved, so I'm closing it.
