### ISSUE TITLE
Holes in type signatures

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#259]
It would be _really_ convenient to allow signatures like

```rust
#[flux::sig(fn() -> Option<_>))
fn foo() -> Option<Option<i32>> { ... }
```

which automatically fill in the _hole_ with the relevant `rustc` thing (here, `Option<i32>`) but I think the current split with `resolver` and `zip_ty` makes rather difficult...

**Comment by nilehmann** [comment]
This was implemented in https://github.com/flux-rs/flux/pull/438
