### ISSUE TITLE
Support `SizeOf` for slices (?)

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#282]
The following currently crashes

```rust
#![feature(register_tool)]
#![register_tool(flux)]

pub fn mk_ten() -> Vec<i32> {
    let v = vec![1,2];
    v
}
``` 

which currently crashes with 

```
error[FLUX]: unsupported statement
 --> flux-tests/tests/todo/vec.rs:5:13
  |
5 |     let v = vec![1,2];
  |             ^^^^^^^^^
  |
  = note: unsupported rvalue `SizeOf([i32; 2])`
  = note: this error originates in the macro `vec` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by nilehmann** [comment]
Supporting `SizeOf` is the least of our problems if we want to support `vec!`. Look at the mir generated for `vec![1, 2]` 

```rust
fn main() -> () {
    let mut _0: ();
    let _1: std::vec::Vec<i32>;
    let mut _2: std::boxed::Box<[i32]>;
    let mut _3: std::boxed::Box<[i32; 2]>;
    let mut _4: usize;
    let mut _5: usize;
    let mut _6: *mut u8;
    let mut _7: std::boxed::Box<[i32; 2]>;
    let mut _8: *const [i32; 2];

    bb0: {
        _4 = const 8_usize;
        _5 = const 4_usize;
        _6 = alloc::alloc::exchange_malloc(move _4, move _5) -> bb1;
    }

    bb1: {
        _7 = ShallowInitBox(move _6, [i32; 2]);
        _8 = (((_7.0: std::ptr::Unique<[i32; 2]>).0: std::ptr::NonNull<[i32; 2]>).0: *const [i32; 2]);
        (*_8) = [const 1_i32, const 2_i32];
        _3 = move _7;
        _2 = move _3 as std::boxed::Box<[i32]> (Pointer(Unsize));
        _1 = slice::<impl [i32]>::into_vec::<std::alloc::Global>(move _2) -> bb2;
    }

    bb2: {
        drop(_1) -> bb3;
    }

    bb3: {
        return;
    }
}
```

List of problems

1. `SizeOf` and `AlignOf` are not supported
2. [`alloc::alloc::exchange_malloc`](https://doc.rust-lang.org/src/alloc/alloc.rs.html#328) returns a raw pointer `*mut u8`. 
3. `ShallowInitBox` coerces `*mut u8` into `Box<↯>` (a box to uninitialized memory)
4. `_2 = move _3 as std::boxed::Box<[i32]> (Pointer(Unsize));` does an unsized coercion between `Box<[i32;2]>` and `Box<[i32]>`

**Comment by ranjitjhala** [comment]
Sadly yes.

We have been "limping" around this problem, e.g. you can write

```rust 
#[path = "../lib/rvec.rs"]
pub mod rvec;
use rvec::RVec;

#[flux::sig(fn() -> RVec<i32>[2])]
pub fn mk_ten() -> RVec<i32> {
    let v = rvec![1,2];
    v
}
```

(where `RVec` is a wrapper around `Vec`)

but yes, I think to be at all practical, we need to just support real `Vec`...

**Comment by ranjitjhala** [comment]
@nilehmann -- rather than have to implement all those low level coercions and what not, can't we at least have a specialized `vec!` that just uses `new` and `push` which is used when compiling with `flux`?

**Comment by nilehmann** [comment]
@ranjitjhala that's and interesting thought. We can have an alternative implementation of `vec!` that expands to something different depending on whether the code is being checked by flux, with the assumption that both expansions are semantically equivalent (up to performance). Although, I think the problem remains because you still have to use an alternative definition and at that point maybe better to just use `RVec`. Specializing the behavior of the definition of `vec!` in the standard library would be hard.

**Comment by ranjitjhala** [comment]
IDK, it seems a lot easier to just 
(a) say "use _this_ definition of `vec!` when `flux`-ing", than to 
(b) pervasively have to change _all_ occurrences of `Vec`.

The latter (b) is clearly a non-starter in practice.

The former (a) seems like it should be possible with some `#ifdef` shenanigans if not cleaner?

**Comment by ranjitjhala** [comment]
having personally done (b) for `wave` its clearly not impossible, but super tedious and impractical, whereas `vec!` probably appears in a few places, and anyways there's probably some (hopefully easy and not too gross!) way to do (a)...

(Unrelated, presumably, people mostly use `vec!` for small vectors -- seems odd to try to hyper optimize the time taken to create a vector of size 3 or 5 or 10 ... ? )

**Comment by nilehmann** [comment]
@TomMD yeah definitely, we need to reduce churn. I was commenting on the idea of hacking around `vec!` by having it expand differently depending on whether flux is running. I don't know of any way we can do that transparently to the user so it would require "customization" (e.g., with a cfg). 

In this case, I think the best is to bite the bullet and implement the missing features to support `vec!` as is. I don't think it'll be terribly difficult, but we have our hands busy with other things. So going back to your original question, yes, the list of problems is still up to date.
