### ISSUE TITLE
Need a check to determine when we pass the `--feature flux-attrs-proc-macros/enabled` flag

### ISSUE THREAD

**Issue by cole-k** [flux-rs/flux#398]
See what Prusti does
https://github.com/viperproject/prusti-dev/blob/master/prusti-utils/src/launch/mod.rs#L291-L322

The issue is that if you don't have a dependency on `flux-attrs-proc-macros`, you won't be able to use `cargo-flux`. You'll get a message like

```
$ cargo-flux check
error: none of the selected packages contains these features: flux-attrs-proc-macros/enabled
```

# Quick fix

Add `flux-attrs-proc-macros` as a dependency (it has to be a local dep for now).

**Comment by nilehmann** [comment]
This is obsolete after https://github.com/flux-rs/flux/pull/547
