### ISSUE TITLE
Handling generics in extern specs

### ISSUE THREAD

**Issue by cole-k** [flux-rs/flux#403]
Simple bug: Right now we assume that any argument to a type in an extern struct is a generic, this should be fixed. We should only collect actual generics and put the actual generics on the dummy struct.

Harder bug: When we generate the function signature for the dummy function for extern functions, we need to add in any generics that are on the external type. For example, for `len`

```rust
#[extern_spec(std::vec::Vec)]
#[flux::sig(fn(&Vec<T>[@n]) -> usize[n])]
fn len(v: &Vec<T>) -> usize;
```

we need to generate a dummy function that has a `<T>` parameter, but notably does not make the interior call `std::vec::Vec::len::<T>()`. i.e. this is what we want

```rust
#[extern_spec]
#[flux::sig(fn(&Vec<T>[@n]) -> usize[n])]
fn flux_extern_len<T>(v: &Vec<T>) -> usize {
    std::vec::Vec::len(v)
}
```

not this

```rust
#[extern_spec]
#[flux::sig(fn(&Vec<T>[@n]) -> usize[n])]
fn flux_extern_len<T>(v: &Vec<T>) -> usize {
    std::vec::Vec::len::<T>(v)
}
```

I think that a reasonable thing to do here would be to require users to specify what generics get passed to the interior call in the extern spec, but I mean we have the information present to add the generics to the dummy function definition in this case, it's just kind of messy.

**Comment by ranjitjhala** [comment]
@nilehmann - isn't this solved? can we close?

**Comment by nilehmann** [comment]
Yes, this is supported now
