### ISSUE TITLE
Cargo-flux check calls flux-driver incorrectly

### ISSUE THREAD

**Issue by TomMD** [flux-rs/flux#463]
I'm trying out flux. After installing (commit ce7386ce09711edf2bdc46e516aeb24b0190dbbb) I run `cargo-flux check` and get:

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/<user>/.cargo/bin/flux-driver /home/<user>/.rustup/toolchains/nightly-2023-06-06-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: multiple input filenames provided (first two filenames are `/home/<user>/.rustup/toolchains/nightly-2023-06-06-x86_64-unknown-linux-gnu/bin/rustc` and `-`)
```

I don't think the target repo matters, but I tried on tommd/toy-rust-symbolic-execution .

**Comment by nilehmann** [comment]
Hi, thanks for reporting. I also noticed this today. Apparently there was a change in the way cargo invokes rustc and it broke when I updated the tool chain here https://github.com/flux-rs/flux/commit/bae0076d8d3803138fda15429790c4d2d7a0927d
