### ISSUE TITLE
error[E0432]: unresolved import `time`

### ISSUE THREAD

**Issue by racherb** [flux-rs/flux#545]
# unresolved import `time`

When running `rustc-flux --crate-type=lib src/generic.rs` the system does not recognize the import of the `time` library and throws the following error:

```bash
error[E0432]: unresolved import `time`
 --> src/generic.rs:5:13
  |
5 |     pub use time::Month as TimeMonth;
  |             ^^^^
  |             |
  |             unresolved import
  |             help: a similar path exists: `std::time`

```

However, the time library is being properly imported as validated by `cargo check`.
Is there some specification for `rustc flux` that I am ignoring?

**Comment by nilehmann** [comment]
Hi @racherb thanks for posting. The `rustc-flux` binary is intended to be used on a single file, it works as if you are calling `rustc` on the file, this means it doesn't know about dependencies. If you want to run flux on a cargo project with dependencies you should run `cargo-flux`.

Some of this is explained in this guide https://flux-rs.github.io/flux/guide/run.html.

**Comment by nilehmann** [comment]
Hi @racherb, are you trying to run flux on a cargo project with the [`time`](https://crates.io/crates/time) crate as a dependency?

The `rustc-flux` binary is intended to be used for single files. It works as if you are calling `rustc` directly on the file. This means it doesn't know anything about dependencies. To run flux on a cargo project with dependencies you should use `cargo-flux`. Some of this is explained in the guide https://flux-rs.github.io/flux/guide/run.html

**Comment by racherb** [comment]
Hi @nilehmann, I understand that under the hood `cargo-flux check` makes use of `rustc`. Anyway I have run "`cargo-flux`" and I get the same error. I share the output of the execution. I have used `liquid-haskell` before and now I would like to incorporate type refinement in Rust through `flux`.

```bash
 Run cargo-flux check
 cargo-flux check
  rustc-flux --crate-type=lib src/generic.rs
  rustc-flux --crate-type=lib src/operations.rs
  rustc-flux --crate-type=lib src/core.rs
  rustc-flux --crate-type=lib src/lib.rs
  shell: /usr/bin/bash -e {0}
  env:
    CARGO_TERM_COLOR: always
 Updating crates.io index
 Downloading crates ...
  Downloaded time-macros v0.2.15
  Downloaded deranged v0.3.9
  Downloaded time-core v0.1.2
  Downloaded powerfmt v0.2.0
  Downloaded itertools v0.11.0
  Downloaded time v0.3.30
    Checking powerfmt v0.2.0
   Compiling time-core v0.1.2
    Checking either v1.9.0
   Compiling time-macros v0.2.15
    Checking deranged v0.3.9
    Checking itertools v0.11.0
    Checking time v0.3.30
    Checking dayendar v0.1.2 (/home/runner/work/dayendar/dayendar)
warning: methods `previous_month`, `next`, `prev`, `forward`, `backward`, and `range_to` are never used
   --> src/generic.rs:217:16
    |
189 |     impl YearMonth {
    |     -------------- methods in this implementation
...
217 |         pub fn previous_month(&self) -> Option<Self> {
    |                ^^^^^^^^^^^^^^
...
227 |         pub fn next(&self) -> Self {
    |                ^^^^
...
240 |         pub fn prev(&self) -> Self {
    |                ^^^^
...
253 |         pub fn forward(&self, months: usize) -> Self {
    |                ^^^^^^^
...
261 |         pub fn backward(&self, months: usize) -> Self {
    |                ^^^^^^^^
...
269 |         pub fn range_to(&self, end: &Self) -> Vec<Self> {
    |                ^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: `dayendar` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 2.15s
error[E0432]: unresolved import `time`
 --> src/generic.rs:5:13
  |
5 |     pub use time::Month as TimeMonth;
  |             ^^^^
  |             |
  |             unresolved import
  |             help: a similar path exists: `std::time`

error[E0433]: failed to resolve: unresolved import
 --> src/generic.rs:8:13
  |
8 |     pub use time::macros::date;
  |             ^^^^
  |             |
  |             unresolved import
  |             help: a similar path exists: `std::time`

error[E0433]: failed to resolve: maybe a missing crate `core`?
 --> src/generic.rs:9:9
  |
9 |     use core::ops::RangeInclusive;
  |         ^^^^ maybe a missing crate `core`?
  |
  = help: consider adding `extern crate core` to use the `core` crate

error[E0432]: unresolved import `time`
 --> src/generic.rs:6:13
  |
6 |     pub use time::{Date as Date, Duration as Duration, Weekday as Weekday};
  |             ^^^^
  |             |
  |             unresolved import
  |             help: a similar path exists: `std::time`

error: cannot determine resolution for the macro `date`
  --> src/generic.rs:20:32
   |
20 |     pub const MIN_DATE: Date = date!(0001 - 01 - 01);
   |                                ^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `date`
  --> src/generic.rs:22:32
   |
22 |     pub const MAX_DATE: Date = date!(9999 - 12 - 31);
   |                                ^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
Error: Process completed with exit code 1.
```

**Comment by nilehmann** [comment]
I'm not sure how to read the output but from this

```
  rustc-flux --crate-type=lib src/generic.rs
  rustc-flux --crate-type=lib src/operations.rs
  rustc-flux --crate-type=lib src/core.rs
  rustc-flux --crate-type=lib src/lib.rs
```

I interpret you are running `rustc-flux` on every file. Is that correct?

That will give you an error because `rustc-flux` doesn't know anything about dependencies, the same way running `rustc --crate-type=lib src/lib.rs` will give you an error.

To run Flux on a cargo project you just need to use `cargo-flux`. That will verify all the files in the project. The way to use `cargo-flux` [has changed recently](https://flux-rs.github.io/flux/guide/run.html#running-on-a-package-cargo-flux), now you have to run it as `cargo flux` and you have to explicitly enable flux in your manifest like so:

```toml
[package.metadata.flux]
enabled = true
```

**Comment by racherb** [comment]
Hi @nilehmann , this solves the problem of dependencies. Thank you very much. 
Unfortunately, I still can't get a clean run with `flux`. Now I get an unsupported type error:

```bash
error[FLUX]: refinement of unsupported associated function
   --> src/generic.rs:136:12
    |
136 |         fn from_str(s: &str) -> Result<Self, Self::Err> {
    |            ^^^^^^^^ this associated function contains unsupported features
    |
    = note: unsupported type: `Self::Err`
    
    error[FLUX]: refinement of unsupported enum
   --> src/core.rs:756:14
    |
756 |     pub enum CalendarPattern {
    |              ^^^^^^^^^^^^^^^ this enum contains unsupported features
    |
    = note: unsupported type: `fn(: Year, : Month, : Day) -> BiDay`
```

**Comment by nilehmann** [comment]
Those are known limitations. 

The first one is easy to work around, you can write the type of the error directly instead of `Self::Err`, for example:

```rust
impl FromStr for SomeType {
    type Err = SomeErr;
    fn from_str(s: &str) -> Result<Self, SomeErr> { ... }
}
```

Unfortunately, there's no workaround for the second one because function pointers are not supported yet.

**Comment by racherb** [comment]
Hi @nilehmann , thanks a lot for the support. **Question**: does it make sense to add the ability or feature to selectively ignore parts of the check with an attribute like `#[flux(skip)]` in `flux`?

**Comment by nilehmann** [comment]
Yes it definitely makes sense to ignore code and we are currently working on it, but ignoring code is a bit more subtle than it may seem.

Right now we have partial support for ignoring code. You can annotate a module with `#![cfg_atrr(flux, flux::ignore)]` to skip checking functions in that module. That however won't prevent the errors you are seeing.

To check a function, Flux needs to know the signature of all it's dependencies even if you are not checking their bodies. If those dependencies don't have a refinement annotations Flux would try to generate what we call a default signature (a rust signature but in a way that Flux can process) and it can fail to do so if it has features currently not supported. That's the kind of errors you are seeing.

Right now we take a simplistic approach where we first generate default signatures for the entire crate and bail out if we encounter any errors before proceeding with the rest of the analysis.

I'm playing with the idea of having what I call a *gradual mode*, where you selectively turn on flux per function and we only process dependencies for the selected functions. This will require a lot of refactoring though as a lot of the code further down the analysis asumes we have signatures for the entire crate.

**Comment by racherb** [comment]
Yes, I understand. The functionality is interesting because the programmer would focus on the use case without first thinking about the limitations of `flux`. I would like to be able to contribute despite my limited free time.

**Comment by nilehmann** [comment]
Agree, I would even go further and say that it is fundamental to ignore code effectively because there's always going to be something we don't support. 

About getting involved. For this particular feature, the first step requires a lot of involvement, but after the first implementation, there may be some smaller remaining issues. I'll definitely let you know!

Something else we can always use help with is improving error messages and documentation. It's particularly useful to get insights from external people pointing out what's confusing.

The other thing that has been on my mind for some time and I would like some help with is improving the way we distribute Flux. I have some big ideas around it (I like what [kani](https://crates.io/crates/kani-verifier) does), but the first step would be to have binary releases for [fixpoint](https://github.com/ucsd-progsys/liquid-fixpoint). I believe building something in Haskell is a high threshold for Rust users. This should be easy, we just need to set up a release workflow in github.

**Comment by nilehmann** [comment]
We have `#[flux::ignore]` now, so I'm closing this.
