### ISSUE TITLE
Encode record sorts as variant in SortCtor

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#548]
Probably better to do it in a different PR, but since record sorts are polymoprphic now we could have them as a variant of `SortCtor`. They are basically sorts automatically generated from a `refined_by` annotation.

_Originally posted by @nilehmann in https://github.com/flux-rs/flux/pull/542#discussion_r1376671901_

**Comment by nilehmann** [comment]
Implemented in https://github.com/flux-rs/flux/commit/a21151289d2620a130f94fb80332264484b1e982
