### ISSUE TITLE
rustc just removed plugins

### ISSUE THREAD

**Issue by safinaskar** [flux-rs/flux#554]
rustc just removed plugins ( https://github.com/rust-lang/rust/pull/116412 ). I hope you are not affected

**Comment by nilehmann** [comment]
Hi @safinaskar. Thanks for the heads up!

Flux is implemented as a [compiler driver](https://rustc-dev-guide.rust-lang.org/rustc-driver.html) so we are not affected by the change. In the context of Rust, when people say compiler plugin they actually mean driver, which has been the standard way to interact with the compiler for some time now and it's unlikely to go away (Clippy and Miri are implemented as a driver)
