### ISSUE TITLE
Feature Request: Using compile-time constants as array lengths

### ISSUE THREAD

**Issue by enjhnsn2** [flux-rs/flux#625]
Hello, it appears that using compile-time constants as array lengths. 
For example, the following code
```Rust
#[flux::constant]
const BUFLEN: usize = 100;
type FixedSizeBuffer = [i32; BUFLEN];
```
fails with the error:
```
error[FLUX]: refinement of unsupported type alias
  --> src/main.rs:36:6
   |
36 |type FixedSizeBuffer = [i32; BUFLEN];
   |      ^^^^ this type alias contains unsupported features
   |
   = note: only interger literals are supported for array lengths
```

You can workaround this by just writing it out as 
```Rust
type FixedSizeBuffer = [i32; 100];
```
directly, but thats a little ugly.

Presumably, adding support for compile-time constant lengths is pretty straight forward, would you mind either (1) implementing it, or (2) pointing me to the appropriate part of the code so that I can implement it?

Thanks

**Comment by nilehmann** [comment]
The easiest way to support this is by opportunistically doing const eval during lifting here https://github.com/flux-rs/flux/blob/main/crates/flux-middle/src/fhir/lift.rs#L540 

Handling more complicated cases like const generics is a bit more involved.

**Comment by ranjitjhala** [comment]
Since we implemented the const generics, is this easier now? It seems this should be pretty straightforward now?

**Comment by nilehmann** [comment]
this is orthogonal to const generics, but I've been looking at it and it sounds doable. I want to implement it. 

I think this is going to be necessary for the eliptic curve stuff because I got this error when running flux on it.
