### ISSUE TITLE
Unsupported higher-rank trait bounds 

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#652]
The following snippet makes `flux` complain

```rust
pub fn foo(x: Vec<i32>) {
    let _blah = x.iter().find(|&&x| x == 0);
}
```

```
error[E0999]: use of unsupported associated function
   --> tests/tests/todo/find00.rs:2:17
    |
2   |     let _blah = x.iter().find(|&&x| x == 0);
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
-Ztrack-diagnostics: created at crates/flux-middle/src/queries.rs:677:29
    |
```

The actual "bound var" seems to be about lifetimes AFAICT ... ?

**Comment by nilehmann** [comment]
The signature for `Iterator::find` is

```rust
    fn find<P>(&mut self, predicate: P) -> Option<Self::Item>
    where
        Self: Sized,
        P: FnMut(&Self::Item) -> bool,
```

The bound `P: FnMut(&Self::Item) -> bool`  corresponds to a [higher-ranked trait bounds](https://doc.rust-lang.org/nomicon/hrtb.html). It (roughly) desugars to the bounds

```rust
for<'a> P: FnMut<&'a Self::Item>
for<'a> <P as FnMut>::Output == bool
```

I think we should fix more fundamental issues about how we treat closure before tackling this.

**Comment by ranjitjhala** [comment]
Yes i think i need to understand what the issues are am quite clueless!
Let’s sync on Monday.

- Ranjit.

**Comment by ranjitjhala** [comment]
Btw @nilehmann - the "higher rank" bit here is the `for <'a>` stuff yes? Because otherwise, this signature looks not that different from, the `rvec::fold` which seems to work fine?

https://github.com/flux-rs/flux/blob/13051f65b1df0bc942ffa0bce466bd44fe30845d/tests/tests/lib/rvec.rs#L125-L127

**Comment by nilehmann** [comment]
Yes, it's about the `for <'a>`, but now that you mention it, it is puzzling because `fold` also uses a higher-rank trait bound.
