### ISSUE TITLE
bug: refining fn output parse error 

### ISSUE THREAD

**Issue by Samir-Rashid** [flux-rs/flux#752]
I believe there is a regression in latest Flux that is triggered when the output of a function signature is nontrivially refined.

```rs
#[flux::sig(fn(n: i32) -> i32[5])]
pub fn five(n: i32) -> i32 {
    n
}
```

```
error: internal compiler error: /home/mod/Documents/github/vtock/flux/crates/flux-infer/src/fixpoint_encoding.rs:415:25: failed to run fixpoint: Custom { kind: UnexpectedEof, error: Error("EOF while parsing a value", line: 1, column: 0) }
  --> src/main.rs:77:1
   |
77 | pub fn five(n: i32) -> i32 {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at /home/mod/Documents/github/vtock/flux/crates/flux-infer/src/fixpoint_encoding.rs:415:25:
Box<dyn Any>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `osfc` (bin "osfc")
```

**Comment by nilehmann** [comment]
This working for me locally. Try updating fixpoint. We recently (3 weeks ago) updated the serialization format between flux and fixpont.

**Comment by Samir-Rashid** [comment]
I already updated everything. I rebuilt it again and the problem got fixed (same up-to-date code). My best guess is I built flux without fixpoint in my path. No clue what happened /shrug

**Comment by Samir-Rashid** [comment]
The problem was due to z3 not being installed.
