### ISSUE TITLE
ICE on FnDef

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#793]
Code like the below 

```rust
#[flux::sig(fn (x:usize) -> usize[x+1])]
fn inc(x: usize) -> usize {
    x + 1
}

#[flux::sig(fn(c: Option<usize[10]>) -> Option<usize[11]>)]
pub fn test(c: Option<usize>) -> Option<usize> {
    c.map(inc)
}
```

triggers 

```
error[E0999]: unsupported terminator
 --> tests/tests/todo/fndef.rs:8:5
  |
8 |     c.map(inc)
  |     ^^^^^^^^^^
-Ztrack-diagnostics: created at crates/flux-middle/src/rustc/lowering.rs:274:34
  |
  = note: unsupported type `FnDef(DefId(0:3 ~ fndef[f288]::inc), [])`
```

Seems to be an issue in both vtock and zkevm...

**Comment by ranjitjhala** [comment]
@nilehmann do you anticipate anything super hard about this one?

**Comment by nilehmann** [comment]
Related to https://github.com/flux-rs/flux/pull/789. We will need to prove that the function implements the `Fn` trait, but the argument that there's nothing refined doesn't hold anymore. The bound on `map` doesn't have refinements but the signature of `inc` does. Not sure how the interaction works

**Comment by ranjitjhala** [comment]
Good point - I’ll just try to push along and see what happens …

- Ranjit.

**Comment by nilehmann** [comment]
The type of `Option::map` is 

```
forall T,U,F: FnOnce(T) -> U. fn(Option<T>, F) -> U
``` 
If we add support for `TyKind::FnDef` we would instantiate the signature to
```
fn(Option<i32{v: $k1}>, {inc}) -> i32{v: $k2}
```
plus the obligation `{inc}: FnOnce(i32{v: $k1}) -> i32{v: $k2}` where `{inc}` is the (singleton) type of the `inc` function.

If we drop the obligation (we don't check function subtyping)  `$k2` would be unconstrained which would be very bad.

**Comment by ranjitjhala** [comment]
Yes indeed that would be bad.

It should suffice to generate a “function subtyping” obligation between
- the (already known) sig for inc
- the template generated for map (with k1, k2 etc)

which itself should be a stepping stone towards the proper handling of
closures?

- Ranjit.
