### ISSUE TITLE
ICE: `TODO: implement for externel crates`

### ISSUE THREAD

**Issue by enjhnsn2** [flux-rs/flux#815]
When I uncomment the `iter` spec in Tock ([here](https://github.com/PLSysSec/tock/blob/master/flux_support/src/extern_specs/iter.rs)), it triggers an ICE:
```
error: internal flux error: crates/flux-middle/src/queries.rs:564:21
  |
  = note: TODO: implement for external crates
```
in the `default_assoc_refinement_def` function. This is presumably just because default assoc refinements haven't been implemented for extern crates.

**Comment by ranjitjhala** [comment]
@enjhnsn2 can you see if the fix works? unfortunately it throws an error elsewhere ... will try to get a nicer message so you can work around it...

**Comment by enjhnsn2** [comment]
This fix worked for the current problem. The error that it throws for me now seems valid (Flux is upset that I didn't define an associated refinement for one of the custom Iterator implementations)
