### ISSUE TITLE
Flux panics when ran on CHECK_OVERFLOW mode on Tock

### ISSUE THREAD

**Issue by enjhnsn2** [flux-rs/flux#816]
When I run `FLUX_CHECK_OVERFLOW=1 cargo flux` in `tock/kernel`, it fails with:
```
thread 'rustc' panicked at crates/flux-refineck/src/primops.rs:48:35:
called `Option::unwrap()` on a `None` value
```
presumably because it cannot find the overflow-enabled version of a primop being used.

I was thinking this would be a good issue for @Samir-Rashid .

To solve this we need to:
1) deduce what primop is missing
2) add it to the tables in  `crates/flux-refineck/src/primops.rs`

**Comment by nilehmann** [comment]
are you interested in working on it @Samir-Rashid? 

I'd recommend changing the `unwrap` and using `tracked_span_bug` instead to know which line in `vtock` is causing the panic.

**Comment by Samir-Rashid** [comment]
Yes. Thanks I'll do that.

**Comment by enjhnsn2** [comment]
@828 fixes this
