### ISSUE TITLE
Check that sorts are used with the correct number of generics

### ISSUE THREAD

**Issue by nilehmann** [flux-rs/flux#820]
Flux happily accepts the following

```rust
use flux_rs::*;

#[refined_by(n: int)]
struct S {
    #[field(i32[n])]
    f: i32,
}

defs! {
    fn foo(s: S<int>) -> int {
        s.n
    }
}
```

This is wrong because the sort `S` (that we automatically generate from the `refined_by` annotation) doesn't have any generics.

We should check sorts are used with the correct number of generics when converting from `fhir` to `rty` [here](https://github.com/flux-rs/flux/blob/68323a45e4da8683da779b80b1e1777d23ad66d8/crates/flux-fhir-analysis/src/conv/mod.rs#L1969)

**Comment by vrindisbacher** [comment]
@nilehmann, Is this still an issue? I can give it a try.

**Comment by nilehmann** [comment]
@vrindisbacher yes, it still is
