### ISSUE TITLE
Check overflows on just 1 file

### ISSUE THREAD

**Issue by enjhnsn2** [flux-rs/flux#827]
I would like to run the equivalent of `FLUX_CHECK_OVERFLOW=1 cargo flux` but only target 1 file. The concrete use case is that I would like to check for overflows on the `ring_buffer.rs` file without having to check overflows everywhere else.

Nico assures me this would be an easy issue for @Samir-Rashid or @vrindisbacher .

**Comment by nilehmann** [comment]
Yes, this would be easy to implement because the internal code is already parametric (per function) on whether to check for overflows, so it's just a matter of exposing it to the user.

**Comment by vrindisbacher** [comment]
I would be open to taking this. I might need to be pointed in the right direction though.

**Comment by nilehmann** [comment]
@vrindisbacher great!

The relevant points are
1. [This function](https://github.com/flux-rs/flux/blob/main/crates/flux-refineck/src/lib.rs#L56) is the entry point to the code that checks a function. It takes a `CheckerConfig` that carries whether to check for overflows. Currently, the `CheckerConfig` is initialized by a global configuration and is the same for all invocations of the function.
2. [This module](https://github.com/flux-rs/flux/blob/main/crates/flux-driver/src/collector/mod.rs) *collects* all flux annotations/attributes. The [ignore and trusted](https://github.com/flux-rs/flux/blob/main/crates/flux-driver/src/collector/mod.rs#L480) annotations are the closest to what we want here.

The one tricky aspect that I don't have a definite answer for is the problem of attaching an annotation to an entire module, but we can ponder this later. This is a problem for ignore/trusted annotations as well, but what we do for them now should suffice for the ring buffer use case (I think).

**Comment by vrindisbacher** [comment]
Thanks @nilehmann! @enjhnsn2, could you provide some detail on how you would expect this to work exactly, i.e. what do you do (add annotations, configs etc.) and what is the expected result?

**Comment by ranjitjhala** [comment]
@vrindisbacher I would suggest something like this:

```
FLUX_CHECK_FILE=path/to/filename.rs cargo flux
```

and then you can see how `FLUX_CHECK_DEF` is implemented and adapt it to this case?

@nilehmann does that sound plausible?

**Comment by nilehmann** [comment]
I think @enjhnsn2 wants something different. He wants to enable overflow checking in a single file/module and leave it disabled elsewhere. So I'm imagining an attribute similar to `#[flux::trusted]`.

Right now you can configure overflow per crate with the attribute `#![flux::cfg(check_overflow=true)]`, I think we want to allow that attribute on any item and, similar to `#[flux::trusted]`, for the attribute to apply recursively. So, if you put it on a module it applies recursively to all functions inside of it. You can use the same attribute to configure `scrape_quals` which could probably have the same behavior.

**Comment by vrindisbacher** [comment]
@enjhnsn2 see #861
