### ISSUE TITLE
Improve error message when a field is accessed in an opaque struct

### ISSUE THREAD

**Issue by nilehmann** [flux-rs/flux#835]
The error message could explain why the field of an opaque struct cannot be accessed and suggest using `#[flux::trusted]`.

[Example of someone confused about it](https://github.com/PLSysSec/tock/pull/3#issuecomment-2384862124)

Relevant pointers:

* https://github.com/flux-rs/flux/blob/199a8ce4324cc86ae2a1fc7d1fa90a51e5817c7d/crates/flux-refineck/src/checker.rs#L1797-L1803
* https://github.com/flux-rs/flux/blob/199a8ce4324cc86ae2a1fc7d1fa90a51e5817c7d/crates/flux-refineck/locales/en-US.ftl#L40-L41

**Comment by vrindisbacher** [comment]
@nilehmann, I can take this if you'd like?

**Comment by nilehmann** [comment]
@vrindisbacher that'd be great! One extra pointer. We use `rustc`'s infrastructure for reporting errors which is documented here https://rustc-dev-guide.rust-lang.org/diagnostics/diagnostic-structs.html

**Comment by vrindisbacher** [comment]
@nilehmann, how does this look?

File:
```rust
#![allow(unused)]
#![allow(dead_code)]

use std::collections::HashMap;

#[flux_rs::opaque]
struct MyStruct {
    inner: u32,
}

impl MyStruct {
    pub fn inner(&self) -> u32 {
        self.inner
    }
}
```

Output:
```rust
error[E0999]: cannot access fields of opaque struct `MyStruct`.
  --> ../opaque_struct.rs:13:9
   |
13 |         self.inner
   |         ^^^^^^^^^^
-Ztrack-diagnostics: created at crates/flux-refineck/src/lib.rs:108:78
   |
help: If you'd like to use fields of `MyStruct` in methods, use `flux::trusted` instead of `flux::opaque`.
  --> ../opaque_struct.rs:7:1
   |
7  | struct MyStruct {
   | ^^^^^^^^^^^^^^^

error: aborting due to 1 previous error
```

**Comment by vrindisbacher** [comment]
Ah I see. Perhaps, the best way to do this is to have a help span over the function suggesting they add `trusted` and then point them to some documentation (maybe in the flux book) about use of `opaque`?

**Comment by nilehmann** [comment]
Pointing to documentation would be cool, we would have to write it though XD

So ideally, we could have something like

```rust
error[E0999]: cannot access fields of opaque struct `MyStruct`.
  --> ../opaque_struct.rs:13:9
   |
13 |         self.inner
   |         ^^^^^^^^^^
-Ztrack-diagnostics: created at crates/flux-refineck/src/lib.rs:108:78
   |
help: try annotating this method with `#[flux::trusted]`
  --> ../opaque_struct.rs:7:1
   |
12 | pub fn inner(&self) -> u32 {
   |        ^^^^^
 note: to know more about opaque http://flux-rs.github.io/....
```
