### ISSUE TITLE
bug: The sort Str is not numeric

### ISSUE THREAD

**Issue by Samir-Rashid** [flux-rs/flux#839]
This is the first issue in what I believe are multiple Flux bugs when it looks at [this huge function](https://github.com/tock/tock/blob/65dda58c893e5b1fb49da7e4389552584758d5e1/arch/rv32i/src/pmp.rs#L2157). I will make an attempt at looking into this, but we will see if I succeed.

<summary>
<details>

```rs
error: internal compiler error: /home/mod/Documents/github/flux/crates/flux-infer/src/fixpoint_encoding.rs:384:43: fixpoint crash: CrashInfo([Array [Array [Array [Number(-1), Null], String("elaborate solver failed on:\n    a870 == a871\nwith error\n    The sort Str is not numeric\n  because\nCannot unify Str with int in expression: a870 == a871 \n  because\nElaborate fails on a870 == a871\nin environment\n    a870 := Str\n\n    a871 := int")]], String(":1:1-1:1: Error\n  elaborate solver failed on:\n      a870 == a871\n  with error\n      The sort Str is not numeric\n  because\nCannot unify Str with int in expression: a870 == a871 \n  because\nElaborate fails on a870 == a871\n  in environment\n      a870 := Str\n\n      a871 := int")])
    --> arch/rv32i/src/pmp.rs:2159:9
     |
2159 | ...   fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Resul...
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at /home/mod/Documents/github/flux/crates/flux-infer/src/fixpoint_encoding.rs:384:43:
Box<dyn Any>
```

</details>
</summary>

I made a minimal reproducer
```rs
struct PmpCfg {
    l: bool,
}

impl PmpCfg {
    fn is_set(&self, flag: char) -> bool {
        match flag {
            'l' => self.l,
            _ => false,
        }
    }
}
```

yields this error
```rs
error: internal compiler error: crates/flux-refineck/src/checker.rs:864:41: expected discr
  --> src/main.rs:67:9
   |
67 |         match flag {
   |         ^^^^^^^^^^

thread 'rustc' panicked at crates/flux-refineck/src/checker.rs:864:41:
Box<dyn Any>
```

**Comment by nilehmann** [comment]
@Samir-Rashid, this sounds like something you could tackle.

A couple of pointers. An even simpler reproduction is

```rust
fn test00(flag: char) {
    match flag {
        'l' => {},
        _ => {},
    }
}
```
and the corresponding mir (you can get the `mir` by setting `FLUX_DUMP_MIR=1`)
```rust
fn test00(_1: char) -> () {
    debug flag => _1;
    let mut _0: ();

    bb0: {
        PlaceMention(_1);
        switchInt(_1) -> [108: bb2, otherwise: bb1];
    }

    bb1: {
        _0 = const ();
        goto -> bb4;
    }

    bb2: {
        falseEdge -> [real: bb3, imaginary: bb1];
    }

    bb3: {
        _0 = const ();
        goto -> bb4;
    }

    bb4: {
        return;
    }
}
```

The problem is `switchInt(_1)` which we check here:

https://github.com/flux-rs/flux/blob/b7fe64142a8d1ebf8c9727ecc27eab11e2725c67/crates/flux-refineck/src/checker.rs#L416-L423

The issue is that we expect the place `_1` to be an int (`is_integral()`), a bool (`is_bool()`), or the discriminant of an ADT (otherwise). We need to extend that also to consider `char`s.

**Comment by nilehmann** [comment]
@Samir-Rashid has this been solved by https://github.com/flux-rs/flux/pull/840 ?

**Comment by Samir-Rashid** [comment]
Closing as completed. This was fixed and a test added in https://github.com/flux-rs/flux/blob/main/tests/tests/pos/structs/enum-match-04.rs (I guess this file is named imprecisely for what it's testing)
