### ISSUE TITLE
bug: fixpoint Cannot unify int with bool

### ISSUE THREAD

**Issue by Samir-Rashid** [flux-rs/flux#841]
#839 is some crazy bug. I have minimized as much as possible. My current hypothesis is that there is some unstable bug in Fixpoint, because seemingly random changes cause the bug to appear and disappear. I require tech support to solve this as I am unable to make the mir small enough for me to inspect.

```rs
enum TORUserPMPCFG {
    OFF,
    TOR,
}

fn fmt2(f: u32, items: [TORUserPMPCFG; 1]) -> u32 {
    let y = f;
    for (i, _) in items.iter().enumerate() {
        let x = (if matches!(TORUserPMPCFG::OFF, TORUserPMPCFG::TOR) {
            1
        } else {
            1
        },);
    }
    0
}

fn main() {}
```

```rs
error: internal compiler error: flux/crates/flux-infer/src/fixpoint_encoding.rs:384:43: 
fixpoint crash: CrashInfo(
[Array [Array [Array [Number(-1), Null], 
String("elaborate solver failed on:
    a10 == a9\nwith error
    The sort bool is not numeric\n  because
Cannot unify int with bool in expression: a10 == a9 
  because
Elaborate fails on a10 == a9
in environment\n    a10 := int

    a9 := bool")]], 
String(":1:1-1:1: Error
  elaborate solver failed on:
      a10 == a9\n  with error
     The sort bool is not numeric
  because
Cannot unify int with bool in expression: a10 == a9 
  because
Elaborate fails on a10 == a9
  in environment
      a10 := int

      a9 := bool")])
  --> src/main.rs:10:1
   |
10 | fn fmt2(f: u32, items: [TORUserPMPCFG; 1]) -> u32 {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at flux/crates/flux-infer/src/fixpoint_encoding.rs:384:43:
Box<dyn Any>
```

**Comment by Samir-Rashid** [comment]
If you change any* character in this code, the bug goes away. I recommend making a tiny change so the bug goes away and then diffing the mir.

For example, left is good, right is panic (this is the only nonidentical part of mir as far as I can tell. `_20` is unused.)
```diff
19,21c19,22
<     let mut _20: bool;
<     let mut _21: TORUserPMPCFG;
<     let mut _22: isize;
---
>     let mut _20: i32;
>     let mut _21: bool;
>     let mut _22: TORUserPMPCFG;
>     let mut _23: isize;
```

**Comment by nilehmann** [comment]
I was able to minimize it a bit more. 

The reason for the randomness is that the bug depends on the shape of the control flow graph and small changes in the code will cause the control flow graph to change

```rust
enum E {
    A,
    B
}

fn test00(items: &[i32]) -> i32 {
     for i in items {
         if matches!(E::A, E::B) { };
     }
     0
}
```
If you run flux with debug assertions enabled you get
```
thread 'rustc' panicked at crates/flux-refineck/src/checker.rs:1671:9:
assertion `left == right` failed
  left: [bindings = a0: int, a1: int, a2: bool, a3: int, reftgenerics = ]
 right: [bindings = a0: int, a1: int, a2: int, a3: bool, reftgenerics = ]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
which is the real cause.

This is quite involved because a fundamental assumption is being broken.

**Comment by nilehmann** [comment]
I found the issue. Thinking about the best way to fix it.

It's related to the order of locals, not to the shape of the CFG as I thought. That explains the randomness even better and the behavior [here](https://github.com/flux-rs/flux/issues/841#issuecomment-2390429796)

**Comment by nilehmann** [comment]
@Samir-Rashid can you confirm if https://github.com/flux-rs/flux/pull/842 fixes the original issue (before minimizing)?

**Comment by Samir-Rashid** [comment]
I have confirmed I an unable to reproduce a crash with any previously crashing code permutation.
