### ISSUE TITLE
Add support for functional updates

### ISSUE THREAD

**Issue by vrindisbacher** [flux-rs/flux#870]
### Motivation

Here is a minimal example to motivate this: 

```rust
#[flux_rs::refined_by(f1: int, f2: int)]
pub struct X {
    #[field(usize[f1])]
    field1: usize,
    #[field(usize[f2])]
    field2: usize,
}

impl X {

    #[flux_rs::sig( fn (self: &strg X[@old_x], usize[@val]) ensures self: X { new_x: new_x.f1 == val })]
    pub fn modify_field1(&mut self, val: usize) {
        self.field1 = val;
    }

    #[flux_rs::sig( fn (self: &strg X[@old_x], usize[@val]) ensures self: X { new_x: new_x.f2 == val })]
    pub fn modify_field2(&mut self, val: usize) {
        self.field2 = val;
    }
}

#[flux_rs::sig(
    fn (self: &strg X[@old_x])
        ensures self: X { new_x: new_x.f1 == 1 && new_x.f2 == 2 }
)]
fn modify_f1_and_f2(x: &mut X) {
    x.modify_field1(1);
    x.modify_field2(2);
}
```

The function `modify_f1_and_f2` cannot be verified: 

```rust
error[E0999]: refinement type error
  --> src/main.rs:27:32
   |
27 |   fn modify_f1_and_f2(x: &mut X) {
   |  ________________________________^
28 | |     x.modify_field1(1);
29 | |     x.modify_field2(2);
30 | | }
   | |_^ a postcondition cannot be proved
   |
note: this is the condition that cannot be proved
  --> src/main.rs:25:34
   |
25 |         ensures self: X { new_x: new_x.f1 == 1 && new_x.f2 == 2 }
   |                                  ^^^^^^^^^^^^^

warning: `flux-issue-sandbox` (bin "flux-issue-sandbox") generated 1 warning
error: could not compile `flux-issue-sandbox` (bin "flux-issue-sandbox") due to 1 previous error; 1 warning emitted
```

Specifically, we lose all information about `f1` when calling `modify_field2`. In order to make this pass, we need to add some information to the post condition of `modify_field1` and `modify_field2`. Mainly, `old_x.f1 == new_x.f1` and `old_x.f2 == new_x.f2` for `modify_field2` and `modify_field1` respectively. 

In small cases like this, this isn't too bad, but in cases where there are many fields it could get quite tedious. 

### Proposal

I suggest we add some kind of support for functional updates on structs. There are a few ways I think this can be done, but unsure what is viable. 

#### Special Function

One way that might be interesting is by adding some primitive definitions for a functional update. This could be an internal, similar to something like `map_store` which automatically adds the necessary "state preservation" expressions in postconditions.

At a high level, it could take in the `old` and `new` objects, along with the fields that should be updated and their corresponding values. For all the fields that should be updated, it would enforce that `new.field == value` and for all other fields it would enforce that `new.field == old.field`

This could be used like so:
```rust
impl X {

    #[flux_rs::sig( fn (self: &strg X[@old_x], usize[@val]) ensures self: X { new_x: functional_update(old_x, new_x, { f1 : val }) })]
    pub fn modify_field1(&mut self, val: usize) {
        self.field1 = val;
    }

    #[flux_rs::sig( fn (self: &strg X[@old_x], usize[@val]) ensures self: X { new_x: functional_update(old_x, new_x, { f2 : val }) })]
    pub fn modify_field2(&mut self, val: usize) {
        self.field2 = val;
    }
}

#[flux_rs::sig(
    fn (self: &strg X[@old_x])
        ensures self: X { new_x: new_x.f1 == 1 && new_x.f2 == 2 }
)]
fn modify_f1_and_f2(x: &mut X) {
    x.modify_field1(1);
    x.modify_field2(2);
}
```
 
#### Add an attribute

Alternatively, we could add an attribute to Flux that changes the Z3 encoding to one that supports these sort of funcitonal updates: 

```rust
#[flux_rs::stateful] // stateful indicates that updates to this struct are functional 
                                // (i.e. only change the precise field they are updating preserving the others
#[flux_rs::refined_by(f1: int, f2: int)]
pub struct X {
    #[field(usize[f1])]
    field1: usize,
    #[field(usize[f2])]
    field2: usize,
}

impl X {

    #[flux_rs::sig( fn (self: &strg X[@old_x], usize[@val]) ensures self: X { new_x: new_x.f1 == val })]
    pub fn modify_field1(&mut self, val: usize) {
        self.field1 = val;
    }

    #[flux_rs::sig( fn (self: &strg X[@old_x], usize[@val]) ensures self: X { new_x: new_x.f2 == val })]
    pub fn modify_field2(&mut self, val: usize) {
        self.field2 = val;
    }
}

// this works now
#[flux_rs::sig(
    fn (self: &strg X[@old_x])
        ensures self: X { new_x: new_x.f1 == 1 && new_x.f2 == 2 }
)]
fn modify_f1_and_f2(x: &mut X) {
    x.modify_field1(1);
    x.modify_field2(2);
}
```

I'm not exactly sure how this would work, but I imagine we would have to change our encoding of structs to use Arrays?

##### Other thoughts

Out of these two, I'd imagine an attribute is probably better. Not sure if anyone has any better thoughts?

**Comment by nilehmann** [comment]
It just occurred to me that Rust already has syntax for functional updates (a.k.a. [struct update syntax](https://doc.rust-lang.org/stable/book/ch05-01-defining-structs.html#creating-instances-from-other-instances-with-struct-update-syntax)) so we can copy that. I'm imagining something like

```rust
    #[flux_rs::sig(
      fn(self: &strg X[@old_x], usize[@val]) 
      ensures self: X { new_x: new_x == X { f1: val, ..old_x } })]
    pub fn modify_field1(&mut self, val: usize) {
        self.field1 = val;
    }
```
or using the value directly as an index
```rust
    #[flux_rs::sig(
      fn(self: &strg X[@old_x], usize[@val]) 
      ensures self: X[X { f1: val, ..old_x }] )]
    pub fn modify_field1(&mut self, val: usize) { ... }
```

I suppose this would need to be accompanied by (regular) constructors that specify all the fields:
```rust
    #[flux_rs::sig(
      fn(self: &strg X[@old_x], usize[@val]) 
      ensures self: X[X { f1: val, f2: old_x.f2 }] )]
    pub fn modify_field1(&mut self, val: usize) { ... }
```
In a way, the real feature is adding constructors. Functional updates can be added as sugar on top of that.

Finally, I think we can do some inference and allow you to write:
```rust
    fn(self: &strg X[@old_x], usize[@val]) 
    ensures self: X[{ f1: val, ..old_x }]  // no need to write X again
      
    fn(self: &strg X[@old_x], usize[@val]) 
    ensures self: X { new_x: new_x ==  { f1: val, ..old_x } }  // no need to write X again
```

**Comment by nilehmann** [comment]
A lot of this (i.e., constructors) is implemented internally but not exposed (coherently) in the surface syntax. For example, we currently allow
```rust
fn(self: &strg X[@old_x], usize[@val])
ensures self: X[old_x.f1, old_x.f2]
```
which desugars to something that's morally equivalent to
```rust
fn(self: &strg X[@old_x], usize[@val])
ensures self: X[{f1: old_x.f1, f2: old_x.f2}]
```
Internally, we check `{f1: old_x.f1, f2: old_x.f2}` as a constructor for an unknown sort we need to infer.

The reason we support `X[old_x.f1, old_x.f2]` is historical. At the very beginning, types had multiple indices. At some point, we decided that all types should be indexed by a single value [^1]. The value may be an _aggregate sort_ and can have multiple fields so we didn't lose expressivity [^2]. At the time I decided to keep the old multi-index syntax (implemented as sugar on top of constructors), but we could remove it if it makes everything more coherent. 

[^1]: More specifically, we went from multiple indices to being indexed by a tuple and then to a different (nominal) sort per type.
[^2]: Having types indexed by a single value is fundamental to the way we do refinements on generic types, so it is not just a matter of taste. This is obvious in retrospect, but it wasn't back then.

**Comment by nilehmann** [comment]
@vrindisbacher I'd start by adding constructors to the syntax of expressions 

https://github.com/flux-rs/flux/blob/689fed1cecc65de6878d246c5f6204a57072b887/crates/flux-syntax/src/surface.rs#L457

and then modifying the parser (let's hope there's no ambiguity)

https://github.com/flux-rs/flux/blob/689fed1cecc65de6878d246c5f6204a57072b887/crates/flux-syntax/src/grammar.lalrpop#L484

This will reveal the various places where we need to add an extra arm to handle the additional case. Most importantly, we will need to add a case when desugaring

https://github.com/flux-rs/flux/blob/689fed1cecc65de6878d246c5f6204a57072b887/crates/flux-desugar/src/desugar.rs#L1358

To implement that we will need to add constructors to fhir as well

https://github.com/flux-rs/flux/blob/689fed1cecc65de6878d246c5f6204a57072b887/crates/flux-middle/src/fhir.rs#L940

That will reveal more places where we need to make changes and so on...

**Comment by nilehmann** [comment]
hmm, on second thought, maybe it's better to start by preparing `fhir` for the changes.

Right now the syntax of refinements expressions in `fhir` is stratified into [`RefineArg`](https://github.com/flux-rs/flux/blob/689fed1cecc65de6878d246c5f6204a57072b887/crates/flux-middle/src/fhir.rs#L606) and [`Expr`](https://github.com/flux-rs/flux/blob/689fed1cecc65de6878d246c5f6204a57072b887/crates/flux-middle/src/fhir.rs#L606). I think it would make everything easier if we remove the stratification and put everything in `Expr`.
